# NWarp configuration file
# Lines starting with # are comments.

host = 0.0.0.0
port = 9090
document_root = ./www
server_name = NWarp
index = index.html
worker_threads = 4
access_log = ./logs/access.log
error_log = ./logs/error.log
